import { connect, StringCodec } from "nats";
const sc = StringCodec();
const nc = await connect({ servers: "nats://10.7.0.4:4222" });
const js = nc.jetstream();
const kv = await js.views.kv("nemo_config");
await kv.put("test.key", sc.encode("test.value"));
console.log("Put successful");
const entry = await kv.get("test.key");
console.log("Got back:", entry ? sc.decode(entry.value) : "null");
await nc.drain();
